import math
def sphereArea(r):
     return 4*math.pi*r**2
def sphereVolume(r):
     return 4*math.pi*r**3/3
def spherematrices(r):
     return sphereArea(r),sphereVolume(r)
def circleArea(r):
     return math.pi*r**2
def squareArea(x):
     return x**2
